### PR TITLE
update to 0.0.20220707223719

### LINKED ISSUE #2: Add windows support

### PR DESCRIPTION
**Pull request by naveen521kk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Also, tries to build on windows, fixes https://github.com/conda-forge/gn-feedstock/issues/2
I need this for https://github.com/conda-forge/staged-recipes/pull/19570

### CODE REVIEW

**Comment by naveen521kk** [comment]
@conda-forge-admin, please rerender

**Comment by naveen521kk** [comment]
Not sure why Travis CI is failing, any idea @xhochy

**Comment by carterbox** [comment]
@naveen521kk, the Travis CI builds a pretty unreliable. Use the conda-forge.yaml to switch from "default" to "azure" for the ppc and arm builds (it shouldn't matter for this build because the tests are just existence tests).

Otherwise, you can try and restart the failed build to see if it doesn't stall.

**Comment by naveen521kk** [comment]
@conda-forge-admin, please rerender

**Comment by naveen521kk** [comment]
> @naveen521kk, the Travis CI builds a pretty unreliable. Use the conda-forge.yaml to switch from "default" to "azure" for the ppc and arm builds (it shouldn't matter for this build because the tests are just existence tests).

Thanks, I've done so.

**Comment by xhochy** [comment]
@conda-forge-admin, please rerender

**Review by xhochy — APPROVED** [review]

**Comment by naveen521kk** [comment]
Thanks!

**Pull request merged**
